services:
  backend:
    build: ./backend
    container_name: project-backend
    hostname: backend-host
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - doc-network

  frontend:
    build: ./frontend
    container_name: project-frontend
    hostname: frontend-host
    environment:
      API_URL: http://backend-host:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - doc-network

networks:
  doc-network:
    driver: bridge
